# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
Post.destroy_all
Comment.destroy_all

user = User.create(username: 'firstAccount', password_digest: BCrypt::Password.create('firstAccount'), display_name: 'firstAccount', bio: 'firstAccount`s bio', img_url: 'https://static.displate.com/857x1200/displate/2023-01-30/6dd78505696a139e8a79efa0e4ee4c6c_f5f3a7e2709f71c53458e7250a0c2aa0.jpg')
user2 = User.create(username: 'secondAccount', password_digest: BCrypt::Password.create('secondAccount'), display_name: 'secondAccount', bio: 'secondAccount`s bio', img_url: 'https://i.imgflip.com/35bdwf.jpg')
user3 = User.create(username: 'thirdAccount', password_digest: BCrypt::Password.create('thirdAccount'), display_name: 'thirdAccount', bio: 'thirdAccount`s bio', img_url: 'https://i.pinimg.com/736x/c6/25/90/c62590c1756680060e7c38011cd704b5.jpg')
user_post = Post.create(title: 'Austria-Hungary and the Ottoman Empire: How Enemies Became Allies', content: 'Austria-Hungary and the Ottoman Empire formed an alliance during World War I out of mutual self-interest. Both empires were facing threats from other powers and saw an opportunity to strengthen their positions by allying with each other. Austria-Hungary was concerned about the influence of Russia in the Balkans, while the Ottoman Empire was wary of Russian expansion in the Caucasus and Central Asia. Additionally, both empires hoped to gain territorial concessions and support from each other in their respective conflicts. Despite their historical differences and conflicts, the strategic considerations of the time led them to form an alliance during the war. Source: https://encyclopedia.1914-1918-online.net/article/islam_in_austria-hungary', img_url: 'https://2.bp.blogspot.com/-RnzpVhjcHiY/UoRoKb7tIjI/AAAAAAAAbWg/zgnMN8a3aYI/s1600/00hapso1.jpg')
user_post2 = Post.create(title: 'John Brown - A Name More People Should Recognize', content: 'John Brown was a fervent abolitionist known for his militant stance against slavery in the United States during the mid-19th century. He gained notoriety for leading the raid on Harpers Ferry in 1859, aiming to initiate a slave rebellion. Brown`s unwavering commitment to the abolitionist cause and his willingness to resort to drastic measures, including violence, to achieve it, made him a polarizing figure in American history. His actions and subsequent trial intensified tensions between North and South and are often cited as contributing factors to the outbreak of the Civil War. Brown`s radical tactics and unyielding dedication to the abolition of slavery have cemented his place as a significant figure in the fight for freedom and equality. Source: https://en.wikipedia.org/wiki/John_Brown_(abolitionist)', img_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/1846-47_John_Brown_by_Augustus_Washington_%28without_frame%29.jpg/220px-1846-47_John_Brown_by_Augustus_Washington_%28without_frame%29.jpg')
comment1 = Comment.create(user_id: user2.id, post_id: user_post.id, content: 'Very interesting, I was not aware of Austra-Hungary`s ties to Islam.')
comment2 = Comment.create(user_id: user.id, post_id: user_post.id, content: 'The Ottoman Empire spread Islamic culture far and wide, I would recommend reading more about it, fascinating time period.', parent_comment_id: comment1.id)
comment3 = Comment.create(user_id: user3.id, post_id: user_post.id, content: 'There is so much culturally intertwined history I haven`t learned yet, thank you for sharing this.')